### PR TITLE
Add support for dhcp-option DOMAIN-SEARCH

### LINKED ISSUE #145: dhcp-option DOMAIN-SEARCH not supported
Only domains from dhcp-option DOMAIN are added to the search list
for compatibility with openvpn2/openvpn3 mixed installations DOMAIN-SEARCH support is needed
I think it should be handled exactly like DOMAIN option is handled currently.

related openvpn ticket: https://community.openvpn.net/openvpn/ticket/1209

### PR DESCRIPTION
**Pull request by stek29**
Fixes #145

### CODE REVIEW

**Comment by stek29** [comment]
I also agree with CLA as specified by signoff in the commit message

**Comment by dsommers** [comment]
It is fine to send pull-requests here for initial reviews, but final patches must (for security and transparency reasons) be submitted to the openvpn-devel mailing list.  For details, see here: https://community.openvpn.net/openvpn/wiki/DeveloperDocumentation

**Comment by stek29** [comment]
@dsommers maybe CONTRIBUTING.rst should be updated to mention that?

https://github.com/OpenVPN/openvpn3/blob/cf6d113337007fb972f7447081f085a5ef87f801/CONTRIBUTING.rst

**Comment by stek29** [comment]
I've sent this patch to openvpn-devel mailing list

**Comment by dsommers** [comment]
Thanks a lot! Patch has been spotted and is in a review queue.  We will also ensure the contribution docs is properly updated.  The CONTRIBUTING.rst file has just been forgotten.

**Comment by dsommers** [comment]
This has been merged with commit 67172a582c1598f1e30fbd3a246251d60618416c.

**Comment by stek29** [comment]
thank you!
btw, how often is openvpn core released?
(and how often openvpn core version is updated in iOS app, just in case you do know it :)

**Comment by schwabe** [comment]
Since the next ios App (3.3) is based on a release branch prior to this commit, it will be in the one after that (3.4). So probably something about  6-12 months from now.

**Pull request closed without merging**
